USE proyecto_terminal;

-- Creacion de tablas de auditoria

Drop table if  exists LOG_AUDITORIA_TERMINAL_C;
CREATE TABLE IF NOT EXISTS LOG_AUDITORIA_TERMINAL_C
(
ID_LOG INT AUTO_INCREMENT ,
NOMBRE_CLIENTE varchar(200),
ID_CLIENTE INT NOT NULL,
NOMBRE_DE_ACCION VARCHAR(10) ,
NOMBRE_TABLA VARCHAR(50) ,
USUARIO VARCHAR(100) ,
FECHA_ACCION DATE ,
HORA_ACCION TIME , 
PRIMARY KEY (ID_LOG)
)
;

drop table if  exists LOG_AUDITORIA_TERMINAL_B;
CREATE TABLE IF NOT EXISTS LOG_AUDITORIA_TERMINAL_B
(
ID_LOG INT AUTO_INCREMENT ,
NOMBRE_BUQUE varchar(100),
ID_BUQUE INT NOT NULL,
IMO INT NOT NULL,
NOMBRE_DE_ACCION VARCHAR(10) ,
NOMBRE_TABLA VARCHAR(50) ,
USUARIO VARCHAR(100) ,
FECHA_ACCION DATE ,
HORA_ACCION TIME , 
PRIMARY KEY (ID_LOG)
)
;

drop table if  exists LOG_AUDITORIA_TERMINAL_B_2;
CREATE TABLE IF NOT EXISTS LOG_AUDITORIA_TERMINAL_B_2
(
ID_LOG INT AUTO_INCREMENT ,
NOMBRE_BUQUE_ANTERIOR varchar(100), 
NOMBRE_BUQUE_ACTUAL varchar(100),
ID_BUQUE INT NOT NULL,
IMO INT NOT NULL,
NOMBRE_DE_ACCION VARCHAR(10) ,
NOMBRE_TABLA VARCHAR(50) ,
USUARIO VARCHAR(100) ,
FECHA_ACCION DATE ,
HORA_ACCION TIME , 
PRIMARY KEY (ID_LOG)
)
;

-- Creación de TRIGGER

-- 1 TRIGGER: Inserción de datos de nuevos clientes en la tabla Cliente


-- DROP TRIGGER TRG_LOG_CLIENTE ;
DELIMITER //
CREATE TRIGGER TRG_LOG_CLIENTE AFTER INSERT ON PROYECTO_TERMINAL.CLIENTE
FOR EACH ROW 
BEGIN

INSERT INTO LOG_AUDITORIA_TERMINAL_C (NOMBRE_CLIENTE, ID_CLIENTE, NOMBRE_DE_ACCION , NOMBRE_TABLA , USUARIO,FECHA_ACCION, HORA_ACCION)
VALUES ( NEW.nombre_cliente  ,NEW.ID_cliente, 'INSERT' , 'CLIENTE' ,CURRENT_USER() , NOW(), CURRENT_TIME());

END//
DELIMITER ;

INSERT INTO cliente (`ID_cliente`,`nombre_cliente`, `direccion_cliente`,`telefono_cliente`, `correo_cliente`) VALUES (10, 'ATLANTIC TRADING & MARKETING INC', '5847 San Felipe St # 2100, Houston, TX 77057, Estados Unidos', '17132432200','presse@totalenergies.com');
INSERT INTO cliente (`ID_cliente`,`nombre_cliente`, `direccion_cliente`,`telefono_cliente`, `correo_cliente`) VALUES (11, 'REPSOL TRADING,S.A', 'Calle Mendez Alvaro, 44, Madrid, 28045 , Madrid', '917538100','carlos.perezdecea@repsol.com');
INSERT INTO cliente (`ID_cliente`,`nombre_cliente`, `direccion_cliente`,`telefono_cliente`, `correo_cliente`) VALUES (12, 'DELTA LIMITED LIABILITY COMPANY', '25, Grekivska str., c. Kharkiv, 61000, Ukraine', '577197788','info@rada.com.ua');
INSERT INTO cliente (`ID_cliente`,`nombre_cliente`, `direccion_cliente`,`telefono_cliente`, `correo_cliente`) VALUES (13, 'CUBAMETALES', 'Calle 10 No. 512 e/ 5ta y 31, Playa, La Habana, Cuba', '5372144341', 'procubainfo@mincex.gob.cu');

SELECT * FROM CLIENTE;
SELECT * FROM LOG_AUDITORIA_TERMINAL_C;


-- 2 TRIGGER: Inserción de datos de nuevas embarcaciones en la tabla buque

-- DROP TRIGGER TRG_LOG_BUQUE ;
DELIMITER //
CREATE TRIGGER TRG_LOG_BUQUE AFTER INSERT ON PROYECTO_TERMINAL.BUQUE
FOR EACH ROW 
BEGIN

INSERT INTO LOG_AUDITORIA_TERMINAL_B (NOMBRE_BUQUE, ID_BUQUE, IMO, NOMBRE_DE_ACCION , NOMBRE_TABLA , USUARIO,FECHA_ACCION, HORA_ACCION)
VALUES ( NEW.nombre_buque  ,NEW.ID_buque, NEW.IMO,'INSERT' , 'CLIENTE' ,CURRENT_USER() , NOW(), CURRENT_TIME());

END//
DELIMITER ;

INSERT INTO buque (`ID_buque`, `IMO`, `nombre_buque`, `categoria_buque`, `tipo_buque`, `bandera`, `TPM`, `largo_total`, `ancho_total`, `ano_construccion`) VALUES (21,9389019, 'MARAN CAPRICORN', 'Crude Oil Tanker', 'VLCC', 'Greece [GR]', '320513.00', '333.00', '60', '2008');

SELECT * FROM BUQUE;
SELECT * FROM LOG_AUDITORIA_TERMINAL_B;


-- 3 TRIGGER: Actualización de datos de embarcaciones en la tabla buque

-- DROP TRIGGER TRG_LOG_BUQUE_II ;
DELIMITER //
CREATE TRIGGER TRG_LOG_BUQUE_II BEFORE UPDATE ON PROYECTO_TERMINAL.BUQUE
FOR EACH ROW 
BEGIN

INSERT INTO LOG_AUDITORIA_TERMINAL_B_2 (NOMBRE_BUQUE_ANTERIOR,NOMBRE_BUQUE_ACTUAL, ID_BUQUE, IMO, NOMBRE_DE_ACCION , NOMBRE_TABLA , USUARIO,FECHA_ACCION, HORA_ACCION)
VALUES ( OLD.nombre_buque , NEW.nombre_buque  , NEW.ID_buque, NEW.IMO,'UPDATE' , 'CLIENTE' ,CURRENT_USER() , NOW(), CURRENT_TIME());

END//
DELIMITER ;

UPDATE proyecto_terminal.buque SET nombre_buque = 'FRONT ULL'  WHERE IMO = 9290309 ; 
UPDATE proyecto_terminal.buque SET nombre_buque = 'VIRGO'   WHERE IMO = 9236250 ; 

SELECT * FROM BUQUE;
SELECT * FROM LOG_AUDITORIA_TERMINAL_B_2;

UPDATE proyecto_terminal.buque SET nombre_buque = 'SEAGRACE'  WHERE IMO = 9290309 ; 
UPDATE proyecto_terminal.buque SET nombre_buque = 'POSEIDON I'   WHERE IMO = 9236250 ; 
